# Generated by Django 4.2.3 on 2023-08-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_user_country_remove_user_id_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscripted',
        ),
    ]
