# Generated by Django 4.2.3 on 2023-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_remove_user_chat_id_remove_user_is_subscripted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='chat_id'),
        ),
    ]
