# Generated by Django 4.2.3 on 2023-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='chat_id'),
        ),
    ]
