# Generated by Django 4.2.3 on 2023-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscripted',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
