stages:
  - deploy
  - test

Deploy to stage:
  stage: deploy
  script:
    - cp $ENV_STAGE .env
    - bash deployment_scripts.sh


test_stage:
  stage: test
  script:
    - cp $ENV_STAGE .env
    - bash deployment_scripts.sh
    - python3 manage.py test

  tags:
    - prod
