stages:
  - deploy
  - test

Deploy to stage:
  stage: deploy
  script:
    - cp $ENV_STAGE .env
    - bash deployment_scripts.sh


test_stage:
  stage: test
  script:
    - cp $ENV_STAGE .env
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - python3 manage.py migrate
    - python3 manage.py collectstatic --noinput
    - python3 manage.py test

  tags:
    - prod
