version: '3.9'

services:
  db:
    image: postgres:14.7-alpine
    restart: always
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    build: .
    command: bash -c "python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"
      && python manage.py migrate
      && python manage.py loaddata data.json
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning
    container_name: redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    container_name: celery
    command: >
      bash -c "celery -A config.celery worker --beat "
      # bash -c "celery -A config.celery worker --beat -l DEBUG  -S django"
    volumes:
      - ./.env:/app/.env
      - .:/app
    links:
      - redis
    restart: always
    depends_on:
      - db
      - redis
      - app

  test:
    build: .
    command: >
      bash -c "python manage.py test
      &&coverage run --source='.' manage.py test
      && coverage report
      && coverage html"
    volumes:
      - ./.env:/app/.env
      - .:/app
    depends_on:
      - db
      - redis
      - app


volumes:
  postgres_data:
  redis_data: