# Generated by Django 4.2.3 on 2023-08-10 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200, verbose_name='Действие')),
                ('time', models.TimeField(verbose_name='Время')),
                ('datetime_start', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время начала рассылки')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('period', models.CharField(choices=[('every 15 minutes', 'каждые 15 минут'), ('hourly', 'ежечасно'), ('daily', 'ежедневно'), ('weekly', 'еженедельно')], default='daily', max_length=16, verbose_name='Периодичность')),
                ('time_for_action', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('last_time_send', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней отправки привычки')),
                ('compensation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение за полезную привычку')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная приятная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='id сообщения')),
                ('message_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='текст сообщения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
