# Generated by Django 4.2.4 on 2023-08-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='last_time_send',
        ),
    ]
