# Generated by Django 4.2.4 on 2023-08-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habits_last_time_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='datetime_start',
        ),
    ]
